[hosts.mercury]
user_pubkey = "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIAvxtKW0rmRBi8J67gLrLv8Zv338AcmZ3P20DePiUfnX collin@mercury"
host_pubkey = "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIIQtMAgPdWwrOzlZT/lEIRQZ+ajhafG9AEJCrF2/bsmN"

wg_pubkey = "JOeHQM6y6znsyze55jjLLMPWAbAyD8rbe04UBL45GiQ="
wg_ip = "10.100.0.5"

[hosts.ganymede]
hostnames = ["ganymede", "192.168.50.2", "williamsfam.us.com"]
ip = "10.100.0.1"
user_pubkey = "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIFeAsRh11Jyv+7Fm4WhzV4XN0LMYQS1/yMbvT+pvFDcd collin@ganymede"
host_pubkey = "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIL9ogXwOPZbAyAq9ecuzJGeRXobWrT9I7icHeEKnpzwB"

wg_ip = "10.100.0.1"
wg_pubkey = "7BdBTJ/FQUOPjSU+Q1Ieg9VqMd2y8BCMqk61I5rMAnY="

caddy-root-ca = '''
-----BEGIN CERTIFICATE-----
MIIBmzCCAUGgAwIBAgIUZOdBpjHNZvJ8XKdFgVYi19a101owCgYIKoZIzj0EAwIw
GzEZMBcGA1UEAwwQR2FueW1lZGUgSG9tZSBDQTAeFw0yNjA4MjIxMjExMDRaFw0z
NjA4MTkxMjExMDRaMBsxGTAXBgNVBAMMEEdhbnltZWRlIEhvbWUgQ0EwWTATBgcq
hkjOPQIBBggqhkjOPQMBBwNCAATme8gCEPAnxmilt/aqZpVClp7J5+3Y++ZSmXqp
ibnTWa7RNhk/GzXZ8Ks0ez1Pc/lTLAYoIbQk6/Gjk4wg7ipbo2MwYTAfBgNVHSME
GDAWgBSapoWPxw4f0+lBQwNHuRtiXiPDbDAPBgNVHRMBAf8EBTADAQH/MA4GA1Ud
DwEB/wQEAwIBBjAdBgNVHQ4EFgQUmqaFj8cOH9PpQUMDR7kbYl4jw2wwCgYIKoZI
zj0EAwIDSAAwRQIhAKD1PjqoVnPdrlLKl6/rr4WG74gG8ND/QpwAdPxon2fnAiBJ
WR/WOxlBMpXQqxF7rttr/+zLAUx1wotKugI8FbdrQA==
-----END CERTIFICATE-----
'''

[hosts.terra]
user_pubkey = "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAINKwMBLWWxpf4jZN3R3iQ7XEAOMq0KAOE/6YN4iTBuJx collin@terra"

wg_pubkey = "CWsD6IJYAbbAX756zb5TlChjEJEm0Q3KpeakfuaZIyA="
wg_ip = "10.100.0.24"

[hosts.saturn]
ip = "192.168.50.3"
jump = "collin@ganymede"
user_pubkey = "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIAUURqA833VJRX59xMsrqsgT4uXCKWRaO+4Q5A4f5Vou admin@saturn"

[hosts.mimas]
ip = "192.168.50.4"
jump = "collin@ganymede"
user_pubkey = "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIJ9g9DIR8aOTOPME41waUoAXDqEWhsgxrHgk8j7HfLkf admin@mimas"

[hosts.tethys]
ip = "192.168.50.5"
jump = "collin@ganymede"
user_pubkey = "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIDBaEvYE22LOXV3KzlFW5g169BBd/gux0GNs5l11mzhM admin@tethys"
